/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.funcionarios;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author claudio
 */
public class FuncionariosCadastro extends javax.swing.JFrame {
    FuncionariosBEAN fb = new FuncionariosBEAN();
    
    public FuncionariosCadastro() {
        initComponents();
        estadoInicial();
        limpaFuncionariosBEAN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoNovo = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoPesquisar = new javax.swing.JButton();
        botaoSalvarAlteracoes = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoCpf = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        campoDataNascimento = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        campoDataAdmissao = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        comboSetor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        campoCargo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoMatricula = new javax.swing.JFormattedTextField();
        campoRg = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campoCEP = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        segunda = new javax.swing.JCheckBox();
        terca = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        comboDia = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        horarioEntrada = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        horarioSaida = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botaoNovo.setText("Novo");
        botaoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoNovoActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoSalvarAlteracoes.setText("Salvar alterações");
        botaoSalvarAlteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarAlteracoesActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(botaoPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvarAlteracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoEditar, botaoExcluir, botaoNovo, botaoPesquisar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botaoNovo)
                    .addComponent(botaoEditar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoPesquisar)
                    .addComponent(botaoSalvarAlteracoes)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(null);

        jLabel1.setText("Matrícula");

        jLabel2.setText("Nome completo");

        jLabel3.setText("CPF");

        try {
            campoCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Data de nascimento");

        jLabel5.setText("Data de admissão");

        jLabel6.setText("Setor");

        comboSetor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "TI", "MÉDICO GERAL", "ENFERMAGEM", "ENFERMAGEM TÉCNICA", "SEGURANÇA", "ATENDIMENTO", "COZINHA", "LIMPEZA" }));

        jLabel7.setText("Cargo");

        jLabel8.setText("Senha de login");

        try {
            campoMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMatriculaActionPerformed(evt);
            }
        });

        try {
            campoRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("RG");

        jLabel13.setText("Endereço");

        jLabel14.setText("Rua");

        jLabel15.setText("Bairro");

        jLabel16.setText("CEP");

        try {
            campoCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoMatricula))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(campoDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5)
                                            .addComponent(campoDataAdmissao, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(campoNome, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoEndereco)
                                    .addComponent(comboSetor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campoBairro)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel15))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(campoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(campoRua)
                                    .addComponent(campoCEP))))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoDataAdmissao, campoDataNascimento});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(campoDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel2);

        jPanel3.setBorder(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dias de trabalho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        segunda.setText("Segunda");
        segunda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                segundaItemStateChanged(evt);
            }
        });

        terca.setText("Terça");
        terca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tercaItemStateChanged(evt);
            }
        });

        quarta.setText("Quarta");
        quarta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                quartaItemStateChanged(evt);
            }
        });

        quinta.setText("Quinta");
        quinta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                quintaItemStateChanged(evt);
            }
        });

        sexta.setText("Sexta");
        sexta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sextaItemStateChanged(evt);
            }
        });

        sabado.setText("Sábado");
        sabado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sabadoItemStateChanged(evt);
            }
        });

        domingo.setText("Domingo");
        domingo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                domingoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(segunda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domingo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segunda)
                    .addComponent(terca)
                    .addComponent(quarta)
                    .addComponent(quinta)
                    .addComponent(sexta)
                    .addComponent(sabado)
                    .addComponent(domingo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hora de trabalho por dia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        jLabel9.setText("Dia:");

        comboDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione..." }));
        comboDia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDiaItemStateChanged(evt);
            }
        });

        jLabel10.setText("Hora de entrada:");

        horarioEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horarioEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                horarioEntradaFocusLost(evt);
            }
        });
        horarioEntrada.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                horarioEntradaPropertyChange(evt);
            }
        });
        horarioEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horarioEntradaKeyPressed(evt);
            }
        });

        jLabel11.setText("Hora de saída:");

        horarioSaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        horarioSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                horarioSaidaFocusLost(evt);
            }
        });
        horarioSaida.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                horarioSaidaPropertyChange(evt);
            }
        });
        horarioSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                horarioSaidaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(horarioSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(comboDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(horarioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(horarioSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados de trabalho", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoActionPerformed
        estadoNovo();
    }//GEN-LAST:event_botaoNovoActionPerformed

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        estadoEditar();
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        estadoCancelar();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoSalvarAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarAlteracoesActionPerformed
        //INSTANCIAR AS FUNÇÕES NECESSÁRIAS-------------------------------------
        FuncionariosDAO fDAO = new FuncionariosDAO();
        FuncionariosBEAN fBEAN = new FuncionariosBEAN();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        //VERIFICA OS ERROS DE INSERÇÃO DE DADOS--------------------------------
        if(campoMatricula.getText().replace(" ", "").equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Matricula'");
            return;
        }
        if(campoNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Nome Completo'");
            return;
        }
        if(campoCpf.getText().replace(".", "").replace("-", "").replace(" ", "").equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'CPF'");
            return;
        }
        if(campoRg.getText().replace(".", "").replace("-", "").equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'RG'");
            return;
        }
        if(campoDataNascimento.getDate().equals(null)){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Data de nascimento'");
            return;
        }
        if(campoDataAdmissao.getDate().equals(null)){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Data de admissão'");
            return;
        }
        if(comboSetor.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Setor'");
            return;
        }   
        if(campoCargo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Cargo'");
            return;
        }
        if(campoSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Senha de login'");
            return;
        }
        if(campoEndereco.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Endereço'");
            return;
        }
        if(campoBairro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Bairro'");
            return;
        }
        if(campoRua.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Rua'");
            return;
        }
        if(campoCEP.getText().replace(".", "").replace("-", "").equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'CEP'");
            return;
        }
        //VERIFICA SE FOI SELECIONADO ALGUM DIA---------------------------------
        if(segunda.isSelected() == false && terca.isSelected() == false && quarta.isSelected() == false &&
            quinta.isSelected() == false && sexta.isSelected() == false && sabado.isSelected() == false &&
            domingo.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Preencha os dias em que o funcionário irá trabalhar");
            return;
        }
        //VERIFICA SE OS HORÁRIOS FORAM INSERIDOS-------------------------------
        if(segunda.isSelected() == true){
            if(fb.getHorarioSegunda() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Segunda'");
                return;
            }else if(fb.getHorarioSegunda().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Segunda'");
            }
        }if(terca.isSelected() == true){
            if(fb.getHorarioTerca() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Terça'");
                return;
            }else if(fb.getHorarioTerca().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Terça'");
                return;
            }
        }if(quarta.isSelected() == true){
            if(fb.getHorarioQuarta() == null){
                JOptionPane.showMessageDialog(null, "Insira  o horário para 'Quarta'");
                return;
            }else if(fb.getHorarioQuarta().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Quarta'");
            }
        }if(quinta.isSelected() == true){
            if(fb.getHorarioQuinta() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Quinta'");
                return;
            }else if(fb.getHorarioQuinta().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Quinta'");
                return;
            }
        }if(sexta.isSelected() == true){
            if(fb.getHorarioSexta() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Sexta'");
                return;
            }else if(fb.getHorarioSexta().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Sexta'");
                return;
            }
        }if(sabado.isSelected() == true){
            if(fb.getHorarioSabado() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Sábado'");
                return;
            }else if(fb.getHorarioSabado().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inserido para 'Sábado'");
                return;
            }
        }if(domingo.isSelected() == true){
            if(fb.getHorarioDomingo() == null){
                JOptionPane.showMessageDialog(null, "Insira o horário para 'Domingo'");
                return;
            }else if(fb.getHorarioDomingo().length() < 11){
                JOptionPane.showMessageDialog(null, "Verifique o horário inseido para 'Domingo'");
                return;
            }
        }
        //VERIFICA REPETIÇÃO DE DADOS-------------------------------------------
        for(FuncionariosBEAN aux : fDAO.verificaRepeticao()){
            if(aux.getMatricula().equals(campoMatricula.getText().replace(" ", ""))){
                JOptionPane.showMessageDialog(null, "A matrícula digitada já existe.");
                return;
            }
            if(aux.getCpf().equals(campoCpf.getText().replace(".", "").replace("-", "").replace(" ", ""))){
                JOptionPane.showMessageDialog(null, "O CPF digitado já existe.");
                return;
            }
            if(aux.getRg().equals(campoRg.getText().replace(".", "").replace("-", "").replace(" ", ""))){
                JOptionPane.showMessageDialog(null, "O RG digitado já existe");
                return;
            }
        }
        //PREENCHE BEAN---------------------------------------------------------
        fBEAN.setMatricula(campoMatricula.getText().replace(" ", ""));
        fBEAN.setNome(campoNome.getText());
        fBEAN.setCpf(campoCpf.getText().replace(".", "").replace("-", "").replace(" ", ""));
        fBEAN.setRg(campoRg.getText().replace(".", "").replace("-", "").replace(" ", ""));
        fBEAN.setDataNascimento(sdf.format(campoDataNascimento.getDate()));
        fBEAN.setDataAdmissao(sdf.format(campoDataAdmissao.getDate()));
        fBEAN.setSetor(comboSetor.getSelectedItem().toString());
        fBEAN.setCargo(campoCargo.getText());
        fBEAN.setSenha(campoSenha.getText());
        fBEAN.setEndereco(campoEndereco.getText());
        fBEAN.setBairro(campoBairro.getText());
        fBEAN.setRua(campoRua.getText());
        fBEAN.setCep(campoCEP.getText().replace(".", "").replace("-", "").replace(" ", ""));
        
        String horarioDefinitivo = null;
        if(domingo.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "1" + fb.getHorarioDomingo();
        }if(segunda.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "2" + fb.getHorarioSegunda();
        }if(terca.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "3" + fb.getHorarioTerca();
        }if(quarta.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "4" + fb.getHorarioQuarta();
        }if(quinta.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "5" + fb.getHorarioQuinta();
        }if(sexta.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "6" + fb.getHorarioSexta();
        }if(sabado.isSelected() == true){
            horarioDefinitivo = horarioDefinitivo + "-" + "7" + fb.getHorarioSabado();
        }
        //SALVA NO BANCO DE DADOS-----------------------------------------------
        fDAO.createFuncionario(fBEAN);
        //EXIBE MENSAGEM DE CONFIRMAÇÃO-----------------------------------------
        JOptionPane.showMessageDialog(null, "A matrícula " + campoMatricula.getText() + " foi adicionada com sucesso.");
        //VOLTA AO ESTADO INICIAL-----------------------------------------------
        estadoSalvarAlteracoes();
    }//GEN-LAST:event_botaoSalvarAlteracoesActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        FuncionariosPesquisa pf = new FuncionariosPesquisa();
        pf.setLocationRelativeTo(null);
        pf.setTitle("Pesquisa de Funcionários");
        pf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        pf.setVisible(true);
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void segundaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_segundaItemStateChanged
        if(segunda.isSelected() == true){
            fb.setSegunda(1);
        }else{
            fb.setSegunda(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_segundaItemStateChanged

    private void tercaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tercaItemStateChanged
        if(terca.isSelected() == true){
            fb.setTerca(1);
        }else{
            fb.setTerca(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_tercaItemStateChanged

    private void quartaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_quartaItemStateChanged
        if(quarta.isSelected() == true){
            fb.setQuarta(1);
        }else{
            fb.setQuarta(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_quartaItemStateChanged

    private void quintaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_quintaItemStateChanged
        if(quinta.isSelected() == true){
            fb.setQuinta(1);
        }else{
            fb.setQuinta(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_quintaItemStateChanged

    private void sextaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sextaItemStateChanged
        if(sexta.isSelected() == true){
            fb.setSexta(1);
        }else{
            fb.setSexta(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_sextaItemStateChanged

    private void sabadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sabadoItemStateChanged
        if(sabado.isSelected() == true){
            fb.setSabado(1);
        }else{
            fb.setSabado(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_sabadoItemStateChanged

    private void domingoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_domingoItemStateChanged
        if(domingo.isSelected() == true){
            fb.setDomingo(1);
        }else{
            fb.setDomingo(0);
        }
        atualizaComboDia();
    }//GEN-LAST:event_domingoItemStateChanged

    private void horarioEntradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horarioEntradaKeyPressed
        
    }//GEN-LAST:event_horarioEntradaKeyPressed

    private void horarioSaidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_horarioSaidaKeyPressed
        
    }//GEN-LAST:event_horarioSaidaKeyPressed

    private void horarioEntradaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_horarioEntradaPropertyChange
        
    }//GEN-LAST:event_horarioEntradaPropertyChange

    private void horarioSaidaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_horarioSaidaPropertyChange
        
    }//GEN-LAST:event_horarioSaidaPropertyChange

    private void comboDiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDiaItemStateChanged
        String horario = null;
        if(comboDia.getSelectedItem() != null){
            String dia = comboDia.getSelectedItem().toString();
            if(dia != "Selecione..."){
                if(dia.equals("Segunda")){
                    if(fb.getHorarioSegunda() != null && fb.getHorarioSegunda().equals("~") == false){
                        horario = fb.getHorarioSegunda();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Terça")){
                    if(fb.getHorarioTerca() != null && fb.getHorarioTerca().equals("~") == false){
                        horario = fb.getHorarioTerca();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Quarta")){
                    if(fb.getHorarioQuarta() != null  && fb.getHorarioQuarta().equals("~") == false){
                        horario = fb.getHorarioQuarta();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Quinta")){
                    if(fb.getHorarioQuinta() != null && fb.getHorarioQuinta().equals("~") == false){
                        horario = fb.getHorarioQuinta();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Sexta")){
                    if(fb.getHorarioSexta() != null && fb.getHorarioSexta().equals("~") == false){
                        horario = fb.getHorarioSexta();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Sábado")){
                    if(fb.getHorarioSabado() != null && fb.getHorarioSabado().equals("~") == false){
                        horario = fb.getHorarioSabado();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }else if(dia.equals("Domingo")){
                    if(fb.getHorarioDomingo() != null && fb.getHorarioDomingo().equals("~") == false){
                        horario = fb.getHorarioDomingo();
                        horarioEntrada.setText(horario.substring(0, 5));
                        horarioSaida.setText(horario.substring(6));
                    }else{
                        horarioEntrada.setText(null);
                        horarioSaida.setText(null);
                    }
                }
            }else{
                horarioEntrada.setText(null);
                horarioSaida.setText(null);
            }
        }
    }//GEN-LAST:event_comboDiaItemStateChanged

    private void campoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMatriculaActionPerformed

    private void horarioEntradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horarioEntradaFocusLost
        if(comboDia.getSelectedItem().toString() != "Selecione..."){
            String dia = comboDia.getSelectedItem().toString();
            if(dia.equals("Segunda")){
                fb.setHorarioSegunda(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Terça")){
                fb.setHorarioTerca(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Quarta")){
                fb.setHorarioQuarta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Quinta")){
                fb.setHorarioQuinta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Sexta")){
                fb.setHorarioSexta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Sábado")){
                fb.setHorarioSabado(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Domingo")){
                fb.setHorarioDomingo(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }
        }
    }//GEN-LAST:event_horarioEntradaFocusLost

    private void horarioSaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_horarioSaidaFocusLost
        if(comboDia.getSelectedItem().toString() != "Selecione..."){
            String dia = comboDia.getSelectedItem().toString();
            if(dia.equals("Segunda")){
                fb.setHorarioSegunda(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Terça")){
                fb.setHorarioTerca(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Quarta")){
                fb.setHorarioQuarta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Quinta")){
                fb.setHorarioQuinta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Sexta")){
                fb.setHorarioSexta(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Sábado")){
                fb.setHorarioSabado(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }else if(dia.equals("Domingo")){
                fb.setHorarioDomingo(horarioEntrada.getText() + "~" + horarioSaida.getText());
            }
        }
    }//GEN-LAST:event_horarioSaidaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionariosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionariosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionariosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionariosCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botaoCancelar;
    public static javax.swing.JButton botaoEditar;
    public static javax.swing.JButton botaoExcluir;
    public static javax.swing.JButton botaoNovo;
    public static javax.swing.JButton botaoPesquisar;
    public static javax.swing.JButton botaoSalvarAlteracoes;
    public static javax.swing.JTextField campoBairro;
    public static javax.swing.JFormattedTextField campoCEP;
    public static javax.swing.JTextField campoCargo;
    public static javax.swing.JFormattedTextField campoCpf;
    public static com.toedter.calendar.JDateChooser campoDataAdmissao;
    public static com.toedter.calendar.JDateChooser campoDataNascimento;
    public static javax.swing.JTextField campoEndereco;
    public static javax.swing.JFormattedTextField campoMatricula;
    public static javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoRg;
    public static javax.swing.JTextField campoRua;
    public static javax.swing.JPasswordField campoSenha;
    public static javax.swing.JComboBox comboDia;
    public static javax.swing.JComboBox comboSetor;
    public static javax.swing.JCheckBox domingo;
    public static javax.swing.JFormattedTextField horarioEntrada;
    public static javax.swing.JFormattedTextField horarioSaida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JCheckBox quarta;
    public static javax.swing.JCheckBox quinta;
    public static javax.swing.JCheckBox sabado;
    public static javax.swing.JCheckBox segunda;
    public static javax.swing.JCheckBox sexta;
    public static javax.swing.JCheckBox terca;
    // End of variables declaration//GEN-END:variables
//ESTADOS DA UI-----------------------------------------------------------------
    public void estadoInicial(){
        botaoNovo.setEnabled(true);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(true);
        botaoSalvarAlteracoes.setEnabled(false);
        botaoCancelar.setEnabled(false);
        
        campoMatricula.setEditable(false);
        campoNome.setEditable(false);
        campoCpf.setEditable(false);
        campoDataNascimento.setEnabled(false);
        campoDataAdmissao.setEnabled(false);
        comboSetor.setEnabled(false);
        campoCargo.setEditable(false);
        campoSenha.setEditable(false);
        campoEndereco.setEditable(false);
        campoRua.setEditable(false);
        campoBairro.setEditable(false);
        campoCEP.setEditable(false);
        
        segunda.setEnabled(false);
        terca.setEnabled(false);
        quarta.setEnabled(false);
        quinta.setEnabled(false);
        sexta.setEnabled(false);
        sabado.setEnabled(false);
        domingo.setEnabled(false);
        comboDia.setEnabled(false);
        horarioEntrada.setEnabled(false);
        horarioSaida.setEnabled(false);
    }
    public static void estadoPosPesquisar(){
        botaoNovo.setEnabled(false);
        botaoEditar.setEnabled(true);
        botaoExcluir.setEnabled(true);
        botaoPesquisar.setEnabled(false);
        botaoSalvarAlteracoes.setEnabled(false);
        botaoCancelar.setEnabled(true);
        
        campoMatricula.setEditable(false);
        campoNome.setEditable(false);
        campoCpf.setEditable(false);
        campoDataNascimento.setEnabled(false);
        campoDataAdmissao.setEnabled(false);
        comboSetor.setEnabled(false);
        campoCargo.setEditable(false);
        campoSenha.setEditable(false);campoEndereco.setEditable(false);
        campoRua.setEditable(false);
        campoBairro.setEditable(false);
        campoCEP.setEditable(false);
        
        segunda.setEnabled(false);
        terca.setEnabled(false);
        quarta.setEnabled(false);
        quinta.setEnabled(false);
        sexta.setEnabled(false);
        sabado.setEnabled(false);
        domingo.setEnabled(false);
        comboDia.setEnabled(false);
        horarioEntrada.setEnabled(false);
        horarioSaida.setEnabled(false);
        
    }   
    public void estadoNovo(){
        botaoNovo.setEnabled(false);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(false);
        botaoSalvarAlteracoes.setEnabled(true);
        botaoCancelar.setEnabled(true);
        
        campoMatricula.setEditable(true);
        campoNome.setEditable(true);
        campoCpf.setEditable(true);
        campoDataNascimento.setEnabled(true);
        campoDataAdmissao.setEnabled(true);
        comboSetor.setEnabled(true);
        campoCargo.setEditable(true);
        campoSenha.setEditable(true);
        campoEndereco.setEditable(true);
        campoRua.setEditable(true);
        campoBairro.setEditable(true);
        campoCEP.setEditable(true);
        
        segunda.setEnabled(true);
        terca.setEnabled(true);
        quarta.setEnabled(true);
        quinta.setEnabled(true);
        sexta.setEnabled(true);
        sabado.setEnabled(true);
        domingo.setEnabled(true);
        comboDia.setEnabled(true);
        horarioEntrada.setEnabled(true);
        horarioSaida.setEnabled(true);
        
        campoMatricula.setText("");
        campoNome.setText("");
        campoCpf.setText("");
        campoDataNascimento.setDate(null);
        campoDataAdmissao.setDate(null);
        comboSetor.setSelectedIndex(0);
        campoCargo.setText("");
        campoSenha.setText("");
        campoEndereco.setText("");
        campoRua.setText("");
        campoBairro.setText("");
        campoCEP.setText("");
        comboDia.setSelectedIndex(0);
        horarioEntrada.setText(null);
        horarioSaida.setText(null);
    }
    public void estadoEditar(){
        botaoNovo.setEnabled(false);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(false);
        botaoSalvarAlteracoes.setEnabled(true);
        botaoCancelar.setEnabled(true);
        
        campoMatricula.setEditable(true);
        campoNome.setEditable(true);
        campoCpf.setEditable(true);
        campoDataNascimento.setEnabled(true);
        campoDataAdmissao.setEnabled(true);
        comboSetor.setEnabled(true);
        campoCargo.setEditable(true);
        campoSenha.setEditable(true);
        campoEndereco.setEditable(true);
        campoRua.setEditable(true);
        campoBairro.setEditable(true);
        campoCEP.setEditable(true);
        
        segunda.setEnabled(true);
        terca.setEnabled(true);
        quarta.setEnabled(true);
        quinta.setEnabled(true);
        sexta.setEnabled(true);
        sabado.setEnabled(true);
        domingo.setEnabled(true);
        comboDia.setEnabled(true);
        horarioEntrada.setEnabled(true);
        horarioSaida.setEnabled(true);
    }
    public void estadoPosExcluir(){
        botaoNovo.setEnabled(true);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(true);
        botaoSalvarAlteracoes.setEnabled(false);
        botaoCancelar.setEnabled(false);
        
        campoMatricula.setEditable(false);
        campoNome.setEditable(false);
        campoCpf.setEditable(false);
        campoDataNascimento.setEnabled(false);
        campoDataAdmissao.setEnabled(false);
        comboSetor.setEnabled(false);
        campoCargo.setEditable(false);
        campoSenha.setEditable(false);
        campoEndereco.setEditable(false);
        campoRua.setEditable(false);
        campoBairro.setEditable(false);
        campoCEP.setEditable(false);
        
        segunda.setEnabled(false);
        terca.setEnabled(false);
        quarta.setEnabled(false);
        quinta.setEnabled(false);
        sexta.setEnabled(false);
        sabado.setEnabled(false);
        domingo.setEnabled(false);
        comboDia.setEnabled(false);
        horarioEntrada.setEnabled(false);
        horarioSaida.setEnabled(false);
        
        campoMatricula.setText("");
        campoNome.setText("");
        campoCpf.setText("");
        campoDataNascimento.setDate(null);
        campoDataAdmissao.setDate(null);
        comboSetor.setSelectedIndex(0);
        campoCargo.setText("");
        campoSenha.setText("");
        campoEndereco.setText("");
        campoRua.setText("");
        campoBairro.setText("");
        campoCEP.setText("");
        comboDia.setSelectedIndex(0);
        horarioEntrada.setText(null);
        horarioSaida.setText(null);
    }
    public void estadoSalvarAlteracoes(){
        botaoNovo.setEnabled(true);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(true);
        botaoSalvarAlteracoes.setEnabled(false);
        botaoCancelar.setEnabled(false);
        
        campoMatricula.setEditable(false);
        campoNome.setEditable(false);
        campoCpf.setEditable(false);
        campoDataNascimento.setEnabled(false);
        campoDataAdmissao.setEnabled(false);
        comboSetor.setEnabled(false);
        campoCargo.setEditable(false);
        campoSenha.setEditable(false);
        campoEndereco.setEditable(false);
        campoRua.setEditable(false);
        campoBairro.setEditable(false);
        campoCEP.setEditable(false);
        
        segunda.setEnabled(false);
        terca.setEnabled(false);
        quarta.setEnabled(false);
        quinta.setEnabled(false);
        sexta.setEnabled(false);
        sabado.setEnabled(false);
        domingo.setEnabled(false);
        comboDia.setEnabled(false);
        horarioEntrada.setEnabled(false);
        horarioSaida.setEnabled(false);
        
    }
    public void estadoCancelar(){
        botaoNovo.setEnabled(true);
        botaoEditar.setEnabled(false);
        botaoExcluir.setEnabled(false);
        botaoPesquisar.setEnabled(true);
        botaoSalvarAlteracoes.setEnabled(false);
        botaoCancelar.setEnabled(false);
        
        campoMatricula.setEditable(false);
        campoNome.setEditable(false);
        campoCpf.setEditable(false);
        campoDataNascimento.setEnabled(false);
        campoDataAdmissao.setEnabled(false);
        comboSetor.setEditable(false);
        campoCargo.setEditable(false);
        campoSenha.setEnabled(false);
        campoEndereco.setEditable(false);
        campoRua.setEditable(false);
        campoBairro.setEditable(false);
        campoCEP.setEditable(false);
        
        segunda.setEnabled(false);
        terca.setEnabled(false);
        quarta.setEnabled(false);
        quinta.setEnabled(false);
        sexta.setEnabled(false);
        sabado.setEnabled(false);
        domingo.setEnabled(false);
        comboDia.setEnabled(false);
        horarioEntrada.setEnabled(false);
        horarioSaida.setEnabled(false);
    }
    
    public void atualizaComboDia(){
        comboDia.removeAllItems();
        comboDia.addItem("Selecione...");
        if(fb.getSegunda() == 1){comboDia.addItem("Segunda");}
        if(fb.getTerca() == 1){comboDia.addItem("Terça");}
        if(fb.getQuarta() == 1){comboDia.addItem("Quarta");}
        if(fb.getQuinta() == 1){comboDia.addItem("Quinta");}
        if(fb.getSexta() == 1){comboDia.addItem("Sexta");}
        if(fb.getSabado() == 1){comboDia.addItem("Sábado");}
        if(fb.getDomingo() == 1){comboDia.addItem("Domingo");}
    }
    public void limpaFuncionariosBEAN(){
        fb.setHorarioSegunda(null);
        fb.setHorarioTerca(null);
        fb.setHorarioQuarta(null);
        fb.setHorarioQuinta(null);
        fb.setHorarioSexta(null);
        fb.setHorarioSabado(null);
        fb.setHorarioDomingo(null);
        
        fb.setSegunda(0);
        fb.setTerca(0);
        fb.setQuarta(0);
        fb.setQuinta(0);
        fb.setSexta(0);
        fb.setSabado(0);
        fb.setDomingo(0);
    }
//------------------------------------------------------------------------------

}
