/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UI.funcionarios;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author claudio
 */
public class FuncionariosPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaFuncionarios
     */
    public FuncionariosPesquisa() {
        initComponents();
        botaoSelecionar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoMatricula = new javax.swing.JFormattedTextField();
        botaoPesquisar = new javax.swing.JButton();
        botaoMostrarTodos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaPesquisa = new javax.swing.JTable();
        botaoSelecionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Matricula:");

        try {
            campoMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoMostrarTodos.setText("Mostrar todos");
        botaoMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMostrarTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(botaoMostrarTodos)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisar)
                    .addComponent(botaoMostrarTodos))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabelaPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Setor", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaPesquisa);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        botaoSelecionar.setText("Selecionar");
        botaoSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoSelecionar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSelecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        //INSTANCIA AS CLASSES--------------------------------------------------
        FuncionariosDAO fDAO = new FuncionariosDAO();
        DefaultTableModel modeloConsulta = (DefaultTableModel) tabelaPesquisa.getModel();
        modeloConsulta.setNumRows(0);
        //VERIFICA SE O CAMPO FOI PREENCHIDO CORRETAMENTE-----------------------
        if(campoMatricula.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo 'Matricula'");
            return;
        }
        //FAZ A PESQUISA NO BANCO E PREENCHE TABELA-----------------------------
        String matricula = campoMatricula.getText().replace(" ", "");
        for(FuncionariosBEAN fBEAN : fDAO.retornaPesquisa(matricula)){
            modeloConsulta.addRow(new Object[]{
                matricula,
                fBEAN.getNome(),
                fBEAN.getSetor(),
                fBEAN.getCargo()
            });
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void tabelaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPesquisaMouseClicked
        botaoSelecionar.setEnabled(true);
    }//GEN-LAST:event_tabelaPesquisaMouseClicked

    private void botaoSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSelecionarActionPerformed
        //INSTANCIA AS CLASSES--------------------------------------------------
        FuncionariosDAO fDAO = new FuncionariosDAO();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        //REALIZA A PESQUISA DADOS PESSOAIS-------------------------------------
       String matricula = tabelaPesquisa.getValueAt(tabelaPesquisa.getSelectedRow(), 0).toString();
        for(FuncionariosBEAN fBEAN : fDAO.preenchePesquisa(matricula)){
            FuncionariosCadastro.campoMatricula.setText(matricula);
            FuncionariosCadastro.campoNome.setText(fBEAN.getNome());
            FuncionariosCadastro.campoCpf.setText(fBEAN.getCpf());
            try {
                FuncionariosCadastro.campoDataNascimento.setDate(sdf.parse(fBEAN.getDataNascimento()));
                FuncionariosCadastro.campoDataAdmissao.setDate(sdf.parse(fBEAN.getDataAdmissao()));
            } catch (ParseException ex) {
                Logger.getLogger(FuncionariosPesquisa.class.getName()).log(Level.SEVERE, null, ex);
            }
            FuncionariosCadastro.comboSetor.setSelectedItem(fBEAN.getSetor());
            FuncionariosCadastro.campoCargo.setText(fBEAN.getCargo());
            FuncionariosCadastro.campoSenha.setText(fBEAN.getSenha());
            FuncionariosCadastro.campoEndereco.setText(fBEAN.getEndereco());
            FuncionariosCadastro.campoBairro.setText(fBEAN.getBairro());
            FuncionariosCadastro.campoRua.setText(fBEAN.getRua());
            FuncionariosCadastro.campoCEP.setText(fBEAN.getCep());
            FuncionariosCadastro.campoRg.setText(fBEAN.getRg());
        }
        //REALIZA PESQUISA DADOS DE TRABALHO------------------------------------
        String disponibilidade = null;
        String aux = null;
        for(FuncionariosBEAN fBEAN : fDAO.retornaDisponibilidade(matricula)){
            disponibilidade = fBEAN.getCargaHorariaSemanal();
            for(int i = 0; i < 7; i++){
                if(disponibilidade.charAt(0) == '1'){
                    aux = disponibilidade.substring(1, 12);
                    FuncionariosCadastro.fb.setHorarioDomingo(aux);
                    FuncionariosCadastro.domingo.setSelected(true);
                }else if(disponibilidade.charAt(0) == '2'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioSegunda(aux);
                    FuncionariosCadastro.segunda.setSelected(true);
                }else if(disponibilidade.charAt(0) == '3'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioTerca(aux);
                    FuncionariosCadastro.terca.setSelected(true);
                }else if(disponibilidade.charAt(0) == '4'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioQuarta(aux);
                    FuncionariosCadastro.quarta.setSelected(true);
                }else if(disponibilidade.charAt(0) == '5'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioQuinta(aux);
                    FuncionariosCadastro.quinta.setSelected(true);
                }else if(disponibilidade.charAt(0) == '6'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioSexta(aux);
                    FuncionariosCadastro.sexta.setSelected(true);
                }else if(disponibilidade.charAt(0) == '7'){
                    aux = disponibilidade.substring(1,12);
                    FuncionariosCadastro.fb.setHorarioSabado(aux);
                    FuncionariosCadastro.sabado.setSelected(true);
                }
                if(disponibilidade.length() >= 11){
                    if(disponibilidade.length() == 12){
                        i = 7;
                    }else{
                       disponibilidade = disponibilidade.substring(13); 
                    }
                }
            }
        }
        //PREENCHE OS DIAS------------------------------------------------------
        FuncionariosCadastro.atualizaComboDia();
        //FECHA A TELA E ATUALIZA OS STATUS-------------------------------------
        FuncionariosCadastro.estadoPosPesquisar();
        this.dispose();
    }//GEN-LAST:event_botaoSelecionarActionPerformed

    private void botaoMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMostrarTodosActionPerformed
        //INSTANCIA AS CLASSES--------------------------------------------------
        FuncionariosDAO fDAO = new FuncionariosDAO();
        DefaultTableModel modeloConsulta = (DefaultTableModel) tabelaPesquisa.getModel();
        modeloConsulta.setNumRows(0);
        //MOSTRA TODOS----------------------------------------------------------
        for(FuncionariosBEAN fBEAN : fDAO.mostraTodos()){
            modeloConsulta.addRow(new Object[]{
                fBEAN.getMatricula(),
                fBEAN.getNome(),
                fBEAN.getSetor(),
                fBEAN.getCargo()
            });
        }
    }//GEN-LAST:event_botaoMostrarTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionariosPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionariosPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionariosPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionariosPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionariosPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoMostrarTodos;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoSelecionar;
    private javax.swing.JFormattedTextField campoMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaPesquisa;
    // End of variables declaration//GEN-END:variables
}
